// Converts the GADM Singapore boundary into SVG paths and projects
// retail-cluster lat/lons into the same coordinate space.
const fs = require("fs");

const geo = JSON.parse(fs.readFileSync(__dirname + "/../sg.json", "utf8"));
const polys = geo.features[0].geometry.coordinates.flat(); // MultiPolygon -> rings

// real-world locations of the retail clusters
const clusters = {
  orchard: [103.8318, 1.3048],
  marina: [103.8590, 1.2835],
  bugis: [103.8530, 1.2966],
  chinatown: [103.8442, 1.2785],
  harbourfront: [103.8222, 1.2654],
  "paya-lebar": [103.8927, 1.3177],
  tampines: [103.9450, 1.3536],
  jurong: [103.7430, 1.3331],
  woodlands: [103.7860, 1.4360],
  serangoon: [103.8718, 1.3506],
  punggol: [103.9021, 1.4063],
  bishan: [103.8485, 1.3600],
};

// drop far-flung southern islets so the main island fills the frame
const centroidLat = (ring) => ring.reduce((s, p) => s + p[1], 0) / ring.length;
const nearby = polys.filter((r) => centroidLat(r) > 1.2);

// bounds from the kept rings only
let minLon = Infinity, maxLon = -Infinity, minLat = Infinity, maxLat = -Infinity;
for (const ring of nearby) for (const [lon, lat] of ring) {
  if (lon < minLon) minLon = lon; if (lon > maxLon) maxLon = lon;
  if (lat < minLat) minLat = lat; if (lat > maxLat) maxLat = lat;
}

const W = 800, H = 430, PAD = 18;
const scale = Math.min((W - 2 * PAD) / (maxLon - minLon), (H - 2 * PAD) / (maxLat - minLat));
const ox = (W - (maxLon - minLon) * scale) / 2;
const oy = (H - (maxLat - minLat) * scale) / 2;
const px = (lon) => +(ox + (lon - minLon) * scale).toFixed(1);
const py = (lat) => +(oy + (maxLat - lat) * scale).toFixed(1);

// drop tiny islets, keep meaningful land
const ringArea = (ring) => {
  let a = 0;
  for (let i = 0; i < ring.length - 1; i++)
    a += ring[i][0] * ring[i + 1][1] - ring[i + 1][0] * ring[i][1];
  return Math.abs(a / 2);
};
const kept = nearby.filter((r) => ringArea(r) > 0.00015);

const paths = kept.map((ring) => {
  let d = `M${px(ring[0][0])},${py(ring[0][1])}`;
  for (let i = 1; i < ring.length; i++) d += `L${px(ring[i][0])},${py(ring[i][1])}`;
  return d + "Z";
});

const projected = Object.fromEntries(
  Object.entries(clusters).map(([id, [lon, lat]]) => [id, { x: px(lon), y: py(lat) }])
);

const out = `// Auto-generated by scripts/genMap.cjs from GADM 4.1 Singapore boundary data.
// viewBox: 0 0 ${W} ${H}

export const MAP_W = ${W};
export const MAP_H = ${H};

export const islandPaths: string[] = ${JSON.stringify(paths, null, 2)};

export const clusterXY: Record<string, { x: number; y: number }> = ${JSON.stringify(projected, null, 2)};
`;
fs.writeFileSync(__dirname + "/../src/data/sgOutline.ts", out);
console.log(`rings kept: ${kept.length}/${polys.length}, total path chars: ${paths.join("").length}`);
